### ISSUE TITLE
Website crash

### ISSUE THREAD

**Issue by Plerx2493** [kuylar/InnerTube#34]
<img width="1337" alt="image" src="https://github.com/kuylar/InnerTube/assets/50530305/33714541-b761-46a6-aca1-f996a7dafd67">

**Comment by kuylar** [comment]
Video seems to be deleted, could not reproduce

**Comment by Plerx2493** [comment]
That could be a regional block [link](https://www.youtube.com/watch?v=S2TaAcwC_zI) works for me

**Comment by Plerx2493** [comment]
But it seems that it works now on tube.kuylar.dev
