### ISSUE TITLE
VideoRenderer.ViewCount should be a number

### ISSUE THREAD

**Issue by MarcusOtter** [kuylar/InnerTube#38]
That way it's easier to filter on it and stuff

**Comment by MarcusOtter** [comment]
Happy to try to implement this,  but if we just replace it from `string` to `long` we lose the "... views" part, which would be different depending on language. So I assume LightTube would no longer be able to draw the UI for views for the different languages?

Should we keep the string around and add another field for the integer? Or how do you think this should be implemented @kuylar

**Comment by kuylar** [comment]
As it would be a breaking change no matter what, for now having something like a `Utils.ParseNumber` could work, as it also could be used in other parts of the code
